[package]
name = "lab01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-time = "1.0.0"
geo = "0.28.0"
ordered-float = "4.2.0"
